### ISSUE TITLE
[kube-up][scale-out] metrics-server pod stuck in CrashLoopBackOff state

### ISSUE THREAD

**Issue by h-w-chen** [CentaurusInfra/arktos#1301]
**What happened**:
after 1x1 kube-up scale-out cluster starts, metric server pod is stuck in CrashLoopBackOff state:
```
$ ./cluster/kubectl.sh --kubeconfig=cluster/kubeconfig.tp-1 get pod -n kube-system -l k8s-app=metrics-server
NAME                                     HASHKEY               READY   STATUS             RESTARTS   AGE
metrics-server-v0.3.3-5f994fcb77-lhq9p   8425696894713785975   1/2     CrashLoopBackOff   7          21m
```

**What you expected to happen**:
pod in Running state

**How to reproduce it (as minimally and precisely as possible)**:
1. starts 1x1 kube-up scale-out cluster;
2. on TP master, run ```kubectl get pod -n kube-system -l k8s-app=metrics-server```

**Anything else we need to know?**:

**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools: kube-up scale-out 1x1
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by h-w-chen** [comment]
here is metrics-server container log:
```
2022-01-24T22:47:41.171510817Z stderr F Flag --deprecated-kubelet-completely-insecure has been deprecated, This is rarely the right option, since it leaves kubelet communication completely insecure.  If you en
counter auth errors, make sure you've enabled token webhook auth on the Kubelet, and if you're in a test cluster with self-signed Kubelet certificates, consider using kubelet-insecure-tls instead.
2022-01-24T22:47:42.114552245Z stderr F I0124 22:47:42.114241       1 serving.go:312] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserve
r.key)
2022-01-24T22:47:42.712761202Z stderr F Error: Unauthorized
2022-01-24T22:47:42.713435138Z stderr F Usage:
2022-01-24T22:47:42.713455251Z stderr F    [flags]
2022-01-24T22:47:42.713460829Z stderr F 
2022-01-24T22:47:42.713465127Z stderr F Flags:
2022-01-24T22:47:42.713471028Z stderr F       --alsologtostderr                                         log to standard error as well as files
2022-01-24T22:47:42.713477458Z stderr F       --authentication-kubeconfig string                        kubeconfig file pointing at the 'core' kubernetes server with enough rights to create tokenaccessreviews.
authentication.k8s.io.
2022-01-24T22:47:42.713482423Z stderr F       --authentication-skip-lookup                              If false, the authentication-kubeconfig will be used to lookup missing authentication configuration from 
the cluster.
2022-01-24T22:47:42.713488994Z stderr F       --authentication-token-webhook-cache-ttl duration         The duration to cache responses from the webhook token authenticator. (default 10s)
2022-01-24T22:47:42.71349528Z stderr F       --authentication-tolerate-lookup-failure                  If true, failures to look up missing authentication configuration from the cluster are not considered fata
l. Note that this can result in authentication that treats all requests as anonymous.
2022-01-24T22:47:42.713500878Z stderr F       --authorization-always-allow-paths strings                A list of HTTP paths to skip during authorization, i.e. these are authorized without contacting the 'core
' kubernetes server.
2022-01-24T22:47:42.713504667Z stderr F       --authorization-kubeconfig string                         kubeconfig file pointing at the 'core' kubernetes server with enough rights to create subjectaccessreview
s.authorization.k8s.io.
2022-01-24T22:47:42.713508454Z stderr F       --authorization-webhook-cache-authorized-ttl duration     The duration to cache 'authorized' responses from the webhook authorizer. (default 10s)
2022-01-24T22:47:42.713511863Z stderr F       --authorization-webhook-cache-unauthorized-ttl duration   The duration to cache 'unauthorized' responses from the webhook authorizer. (default 10s)
2022-01-24T22:47:42.713521364Z stderr F       --bind-address ip                                         The IP address on which to listen for the --secure-port port. The associated interface(s) must be reachab
le by the rest of the cluster, and by CLI/web clients. If blank, all interfaces will be used (0.0.0.0 for all IPv4 interfaces and :: for all IPv6 interfaces). (default 0.0.0.0)
2022-01-24T22:47:42.713526274Z stderr F       --cert-dir string                                         The directory where the TLS certs are located. If --tls-cert-file and --tls-private-key-file are provided
, this flag will be ignored. (default "apiserver.local.config/certificates")
2022-01-24T22:47:42.713530303Z stderr F       --client-ca-file string                                   If set, any request presenting a client certificate signed by one of the authorities in the client-ca-fil
e is authenticated with an identity corresponding to the CommonName of the client certificate.
2022-01-24T22:47:42.713535434Z stderr F       --contention-profiling                                    Enable lock contention profiling, if profiling is enabled
2022-01-24T22:47:42.713539335Z stderr F   -h, --help                                                    help for this command
2022-01-24T22:47:42.713543003Z stderr F       --http2-max-streams-per-connection int                    The limit that the server gives to clients for the maximum number of streams in an HTTP/2 connection. Zer
o means to use golang's default.
2022-01-24T22:47:42.713567597Z stderr F       --kubeconfig string                                       The path to the kubeconfig used to connect to the Kubernetes API server and the Kubelets (defaults to in-
cluster config)
2022-01-24T22:47:42.713571393Z stderr F       --kubelet-certificate-authority string                    Path to the CA to use to validate the Kubelet's serving certificates.
2022-01-24T22:47:42.713574794Z stderr F       --kubelet-insecure-tls                                    Do not verify CA of serving certificates presented by Kubelets.  For testing purposes only.
2022-01-24T22:47:42.713578113Z stderr F       --kubelet-port int                                        The port to use to connect to Kubelets. (default 10250)
2022-01-24T22:47:42.713581646Z stderr F       --kubelet-preferred-address-types strings                 The priority of node address types to use when determining which address to use to connect to a particula
r node (default [Hostname,InternalDNS,InternalIP,ExternalDNS,ExternalIP])
2022-01-24T22:47:42.713584916Z stderr F       --log-flush-frequency duration                            Maximum number of seconds between log flushes (default 5s)
2022-01-24T22:47:42.713588763Z stderr F       --log_backtrace_at traceLocation                          when logging hits line file:N, emit a stack trace (default :0)
2022-01-24T22:47:42.713592237Z stderr F       --log_dir string                                          If non-empty, write log files in this directory
2022-01-24T22:47:42.713606115Z stderr F       --log_file string                                         If non-empty, use this log file
2022-01-24T22:47:42.713610031Z stderr F       --logtostderr                                             log to standard error instead of files (default true)
2022-01-24T22:47:42.71361324Z stderr F       --metric-resolution duration                              The resolution at which metrics-server will retain metrics. (default 1m0s)
2022-01-24T22:47:42.713616827Z stderr F       --profiling                                               Enable profiling via web interface host:port/debug/pprof/ (default true)
2022-01-24T22:47:42.713620249Z stderr F       --requestheader-allowed-names strings                     List of client certificate common names to allow to provide usernames in headers specified by --requesthe
ader-username-headers. If empty, any client certificate validated by the authorities in --requestheader-client-ca-file is allowed.
2022-01-24T22:47:42.71362592Z stderr F       --requestheader-client-ca-file string                     Root certificate bundle to use to verify client certificates on incoming requests before trusting username
s in headers specified by --requestheader-username-headers. WARNING: generally do not depend on authorization being already done for incoming requests.
2022-01-24T22:47:42.713630641Z stderr F       --requestheader-extra-headers-prefix strings              List of request header prefixes to inspect. X-Remote-Extra- is suggested. (default [x-remote-extra-])
2022-01-24T22:47:42.713633994Z stderr F       --requestheader-group-headers strings                     List of request headers to inspect for groups. X-Remote-Group is suggested. (default [x-remote-group])
2022-01-24T22:47:42.713637264Z stderr F       --requestheader-username-headers strings                  List of request headers to inspect for usernames. X-Remote-User is common. (default [x-remote-user])
2022-01-24T22:47:42.713640719Z stderr F       --secure-port int                                         The port on which to serve HTTPS with authentication and authorization.If 0, don't serve HTTPS at all. (d
efault 443)
2022-01-24T22:47:42.713644104Z stderr F       --skip_headers                                            If true, avoid header prefixes in the log messages
2022-01-24T22:47:42.713647326Z stderr F       --stderrthreshold severity                                logs at or above this threshold go to stderr
2022-01-24T22:47:42.713655603Z stderr F       --tls-cert-file string                                    File containing the default x509 Certificate for HTTPS. (CA cert, if any, concatenated after server cert)
. If HTTPS serving is enabled, and --tls-cert-file and --tls-private-key-file are not provided, a self-signed certificate and key are generated for the public address and saved to the directory specified by --
cert-dir.
2022-01-24T22:47:42.713663072Z stderr F       --tls-cipher-suites strings                               Comma-separated list of cipher suites for the server. If omitted, the default Go cipher suites will be us
e.  Possible values: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_S
HA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_RC4_128_SHA,TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES
_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_RC4_128_SHA,TLS_RSA_WITH_3DES_EDE_CBC_SHA,TLS_RSA_WITH_AES_128_C
BC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_RC4_128_SHA
2022-01-24T22:47:42.713668391Z stderr F       --tls-min-version string                                  Minimum TLS version supported. Possible values: VersionTLS10, VersionTLS11, VersionTLS12
2022-01-24T22:47:42.713671795Z stderr F       --tls-private-key-file string                             File containing the default x509 private key matching --tls-cert-file.
2022-01-24T22:47:42.71371186Z stderr F       --tls-sni-cert-key namedCertKey                           A pair of x509 certificate and private key file paths, optionally suffixed with a list of domain patterns 
which are fully qualified domain names, possibly with prefixed wildcard segments. If no domain patterns are provided, the names of the certificate are extracted. Non-wildcard matches trump over wildcard matche
s, explicit domain patterns trump over extracted names. For multiple key/certificate pairs, use the --tls-sni-cert-key multiple times. Examples: "example.crt,example.key" or "foo.crt,foo.key:*.foo.com,foo.com"
. (default [])
2022-01-24T22:47:42.713717132Z stderr F   -v, --v Level                                                 number for the log level verbosity
2022-01-24T22:47:42.713720527Z stderr F       --vmodule moduleSpec                                      comma-separated list of pattern=N settings for file-filtered logging
2022-01-24T22:47:42.713723714Z stderr F 
2022-01-24T22:47:42.715698028Z stderr F panic: Unauthorized
2022-01-24T22:47:42.715723348Z stderr F 
2022-01-24T22:47:42.715752777Z stderr F goroutine 1 [running]:
2022-01-24T22:47:42.715758666Z stderr F main.main()
2022-01-24T22:47:42.715765297Z stderr F         /go/src/github.com/kubernetes-incubator/metrics-server/cmd/metrics-server/metrics-server.go:39 +0x13b
```

**Comment by Sindica** [comment]
New log:

{"log":"panic: Get https://10.0.0.1:443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication: dial tcp 10.0.0.1:443: i/o timeout\n","stream":"stderr","time":"2022-02-25T04:23:38.033590431Z"}

**Comment by Sindica** [comment]
I think this issue is resolved with API server connectivity issue resolved.
