### ISSUE TITLE
Kube-apiserver.log: panic.go:522] PATCH /api/v1/nodes/hollow-node-wht2t/status: (1m0.00203311s) 504

### ISSUE THREAD

**Issue by sonyafenge** [CentaurusInfra/arktos#682]
**What happened**:
started 5k nodes run and cluster crashed with this error
```
I0904 11:22:58.953841       1 panic.go:522] PATCH /api/v1/nodes/hollow-node-wht2t/status: (1m0.00203311s) 504
goroutine 119280 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc083ca09a0, 0x1f8)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:204 +0xc8
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc083ca09a0, 0x1f8)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:183 +0x35
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).WriteHeader(0xc2a55a3840, 0x1f8)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:209 +0xa6
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.(*auditResponseWriter).WriteHeader(0xc02d3f8d20, 0x1f8)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/audit.go:219 +0x63
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.(*ResponseWriterDelegator).WriteHeader(0xc04306b500, 0x1f8)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:376 +0x45
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.httpResponseWriterWithInit.Write(0x0, 0x41d112b, 0x10, 0x1f8, 0x76ffdc0, 0xc0840d1260, 0xc76faeb500, 0xbb, 0x14ea, 0xc2aedcb4f0, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:51 +0x1ba
encoding/json.(*Encoder).Encode(0xc2aedcb5f0, 0x40f3d60, 0xc7a9917900, 0x6, 0x0)
        /usr/local/go/src/encoding/json/stream.go:225 +0x1cb
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Encode(0xc000502b00, 0x76bbbc0, 0xc7a9917900, 0x76aa920, 0xc7acd85530, 0x343e161, 0x6)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go:311 +0x2e4
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Encode(0xc7a736efc0, 0x76bbbc0, 0xc7a9917900, 0x76aa920, 0xc7acd85530, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:215 +0x307
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.SerializeObject(0x41d112b, 0x10, 0x7fcb002efc58, 0xc7a736efc0, 0x76ffdc0, 0xc0840d1260, 0xc2abffc700, 0x1f8, 0x76bbbc0, 0xc7a9917900)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:103 +0x11b
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.WriteObjectNegotiated(0x7702f40, 0xc0014d73e0, 0x7703280, 0xa3d47c0, 0x0, 0x0, 0x41b59a0, 0x2, 0x76ffdc0, 0xc0840d1260, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:137 +0x559
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.ErrorNegotiated(0x76a6620, 0xc7a9917860, 0x7702f40, 0xc0014d73e0, 0x0, 0x0, 0x41b59a0, 0x2, 0x76ffdc0, 0xc0840d1260, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:156 +0x167
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.(*RequestScope).err(...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:84
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.PatchResource.func1(0x76ffdc0, 0xc0840d1260, 0xc2abffc700)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/patch.go:230 +0x270a
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints.restfulPatchResource.func1(0xc04306b3b0, 0xc2b06801e0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/installer.go:1291 +0x99
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1(0xc04306b3b0, 0xc2b06801e0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:272 +0x254
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc000e090e0, 0x76ffcc0, 0xc081edeae8, 0xc2abffc700)
...
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
configuration change:
1. ETCD_SNAPSHOT_COUNT to 5000
2. Run "sudo ionice -c2 -n0 -p pgrep etcd" on kubemark master
```
sonyali@sonya-uswest2:~/go/src/k8s.io/arktos$ git diff
diff --git a/cluster/gce/manifests/etcd.manifest b/cluster/gce/manifests/etcd.manifest
index c9049da..ef000ba 100644
--- a/cluster/gce/manifests/etcd.manifest
+++ b/cluster/gce/manifests/etcd.manifest
@@ -45,7 +45,7 @@
         "value": "{{ etcd_protocol }}://{{ hostname }}:{{ server_port }}"
       },
       { "name": "ETCD_SNAPSHOT_COUNT",
-        "value": "10000"
+        "value": "5000"
       }
         ],
     "livenessProbe": {
```
```
etcd-3a1w1e-kubemark-master /var/log # sudo ionice -c2 -n0 -p `pgrep etcd`
```
logs can be found under GCP project: workload-controller-manager:
```
sonya-uswest2:  /home/sonyali/logs/perf-test/gce-5000/arktos/0903-etcd-3a1w1e 
```
**Environment**:
- Arktos version (use `kubectl version`):
```
sonyali@sonya-uswest2:~/go/src/k8s.io/arktos$ git log
commit 64e1a0f3ad7fe3ed796efe864c451915753d7dc5
Author: chenqianfzh <51831990+chenqianfzh@users.noreply.github.com>
Date:   Wed Aug 26 14:41:36 2020 -0700

    remove old script based multi-tenancy e2e tests (#625)

commit 9542cf281ceb107c70298156f4e8bfe3d268f611
{
Author: sonyafenge <45471193+sonyafenge@users.noreply.github.com>
Date:   Wed Aug 26 11:03:21 2020 -0700

    fix ALLOWED_NOTREADY_NODES for kubemark (#623)

    Co-authored-by: SONYALI <sonyali@Sonyas-MacBook-Pro.local>

commit 487e2fc1401d5b66327c498f67af6b91a6414280
Author: chenqianfzh <51831990+chenqianfzh@users.noreply.github.com>
Date:   Tue Aug 25 23:05:45 2020 -0700

    Rewrite multi-tenancy e2e test tool in golang (#614)

    * Rewrite multi-tenancy e2e test tool in golang

    * make update

    * address comments
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by sonyafenge** [comment]
```
I0904 11:22:58.956548       1 wrap.go:47] GET /api/v1/tenants/system/namespaces/axmuzk-testns/configmaps?fieldSelector=metadata.name%3Dsmall-deployment-20&limit=500&resourceVersion=0: (37.664329007s) 200 [kubemark/v2.7.4 (linux/amd64) kubernetes/64e1a0f 10.64.17.87:35682]
E0904 11:22:21.770257       1 metrics.go:96] Error in audit plugin 'buffered' affecting 1 audit events: audit buffer queue blocked
Impacted events:
2020-09-04T11:22:21.51379443Z AUDIT: id="f9253dff-cffe-4a35-920f-ff46048112d0" stage="ResponseComplete" ip="10.64.34.56" method="list" user="kubecfg" groups="\"system:masters\",\"system:authenticated\"" as="<self>" asgroups="<lookup>" namespace="h531pu-testns" uri="/api/v1/tenants/system/namespaces/h531pu-testns/secrets?fieldSelector=metadata.name%3Ddefault-token-9vtmb&limit=500&resourceVersion=0" response="200"
I0904 11:22:58.956661       1 wrap.go:47] GET /api/v1/tenants/system/namespaces/h531pu-testns/secrets?fieldSelector=metadata.name%3Ddefault-token-9vtmb&limit=500&resourceVersion=0: (37.527132162s) 200 [kubemark/v2.7.4 (linux/amd64) kubernetes/64e1a0f 10.64.34.56:36900]
I0904 11:22:58.957118       1 panic.go:522] PATCH /api/v1/nodes/hollow-node-h7cqt/status?timeout=10s: (1m2.525908519s) 500
goroutine 72380 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc043ac1340, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:204 +0xc8
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc043ac1340, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:183 +0x35
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).WriteHeader(0xc01869f940, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:209 +0xa6
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.(*auditResponseWriter).WriteHeader(0xc02f9bab90, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/audit.go:219 +0x63
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.(*ResponseWriterDelegator).WriteHeader(0xc080260600, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:376 +0x45
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.httpResponseWriterWithInit.Write(0x0, 0x4224208, 0x23, 0x1f4, 0x76ffdc0, 0xc03c19fe60, 0xc0834958b0, 0x40, 0x47, 0xc2b1231490, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:51 +0x1ba
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/protobuf.(*Serializer).Encode(0xc000502bc0, 0x76bbbc0, 0xc6c5b71180, 0x76aa920, 0xc6c7c6f470, 0x343e161, 0x6)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/protobuf/protobuf.go:218 +0x452
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Encode(0xc5c2873560, 0x76bbbc0, 0xc6c5b71180, 0x76aa920, 0xc6c7c6f470, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:215 +0x307
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.SerializeObject(0x4224208, 0x23, 0x7fcb002efc58, 0xc5c2873560, 0x76ffdc0, 0xc03c19fe60, 0xc2b262c700, 0x1f4, 0x76bbbc0, 0xc6c5b71180)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:103 +0x11b
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.WriteObjectNegotiated(0x7702f40, 0xc0014d73e0, 0x7703280, 0xa3d47c0, 0x0, 0x0, 0x41b59a0, 0x2, 0x76ffdc0, 0xc03c19fe60, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:137 +0x559
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.ErrorNegotiated(0x76a0f40, 0xc000156230, 0x7702f40, 0xc0014d73e0, 0x0, 0x0, 0x41b59a0, 0x2, 0x76ffdc0, 0xc03c19fe60, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:156 +0x167
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.(*RequestScope).err(...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:84
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.PatchResource.func1(0x76ffdc0, 0xc03c19fe60, 0xc2b262c700)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/patch.go:230 +0x270a
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints.restfulPatchResource.func1(0xc080260570, 0xc2b35b3500)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/installer.go:1291 +0x99
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1(0xc080260570, 0xc2b35b3500)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:272 +0x254
```

**Comment by sonyafenge** [comment]
```
sonyali@sonya-uswest2:~/go/src/k8s.io/arktos$ kubectl describe pods hollow-node-wht2t -n kubemark
Name:           hollow-node-wht2t
Namespace:      kubemark
Tenant:         system
Priority:       0
Node:           etcd-3a1w1e-minion-group-s172/10.40.0.21
Start Time:     Thu, 03 Sep 2020 22:18:33 +0000
Labels:         name=hollow-node
Annotations:    <none>
Status:         Running
IP:             10.64.18.57
Controlled By:  ReplicationController/hollow-node
Init Containers:
  init-inotify-limit:
    Container ID:  unknown://8dab8f20514d5ce477f944b443a0d542831b05292807e571d4975e7f94283dad
    Image:         busybox
    Image ID:      docker-pullable://busybox@sha256:c2d41d2ba6d8b7b4a3ffec621578eb4d9a0909df29dfa2f6fd8a2e5fd0836aed
    Port:          <none>
    Host Port:     <none>
    Command:
      sysctl
      -w
      fs.inotify.max_user_instances=1000
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 03 Sep 2020 22:18:34 +0000
      Finished:     Thu, 03 Sep 2020 22:18:34 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-8sfvh (ro)
Containers:
  hollow-kubelet:
    Container ID:  unknown://e38fa901ac5535e2cfc641d17735839585042a09544ee744ba0fd3056efdf032
    Image:         gcr.io/workload-controller-manager/kubemark:e4jpra
    Image ID:      docker-pullable://gcr.io/workload-controller-manager/kubemark@sha256:800505439f233a84d5dd54d3ed20f128c5363e4094839a34842a19218c43e3d1
    Ports:         4194/TCP, 10250/TCP, 10255/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP
    Command:
      /bin/sh
      -c
      /kubemark --morph=kubelet --name=$(NODE_NAME)  --v=4 --v=4 --kubeconfig=/kubeconfig/kubelet.kubeconfig $(CONTENT_TYPE) --alsologtostderr 1>>/var/log/kubelet-$(NODE_NAME).log 2>&1
    State:          Running
      Started:      Fri, 04 Sep 2020 09:12:48 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Thu, 03 Sep 2020 22:18:35 +0000
      Finished:     Fri, 04 Sep 2020 09:12:45 +0000
    Ready:          True
    Restart Count:  1
    Requests:
      cpu:     40m
      memory:  100M
    Environment:
      CONTENT_TYPE:  <set to the key 'content.type' of config map 'node-configmap'>  Optional: false
      NODE_NAME:     hollow-node-wht2t (v1:metadata.name)
    Mounts:
      /kubeconfig from kubeconfig-volume (ro)
      /var/log from logs-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-8sfvh (ro)
  hollow-proxy:
    Container ID:  unknown://a75a1c715d03571367a9c70da1c1d2b55d25e8102dac13cac676bf04ebbe3262
    Image:         gcr.io/workload-controller-manager/kubemark:e4jpra
    Image ID:      docker-pullable://gcr.io/workload-controller-manager/kubemark@sha256:800505439f233a84d5dd54d3ed20f128c5363e4094839a34842a19218c43e3d1
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      /kubemark --morph=proxy --name=$(NODE_NAME)  --v=4 --v=4 --kubeconfig=/kubeconfig/kubeproxy.kubeconfig $(CONTENT_TYPE) --alsologtostderr 1>>/var/log/kubeproxy-$(NODE_NAME).log 2>&1
    State:          Running
      Started:      Thu, 03 Sep 2020 22:18:36 +0000
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:     50m
      memory:  352400Ki
    Environment:
      CONTENT_TYPE:  <set to the key 'content.type' of config map 'node-configmap'>  Optional: false
      NODE_NAME:     hollow-node-wht2t (v1:metadata.name)
    Mounts:
      /kubeconfig from kubeconfig-volume (ro)
      /var/log from logs-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-8sfvh (ro)
  hollow-node-problem-detector:
    Container ID:  unknown://32050a6c27648c23bd058c932f5b848349117d6e2e9796511098f3b115d21dcf
    Image:         k8s.gcr.io/node-problem-detector:v0.4.1
    Image ID:      docker-pullable://k8s.gcr.io/node-problem-detector@sha256:f95cab985c26b2f46e9bd43283e0bfa88860c14e0fb0649266babe8b65e9eb2b
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      /node-problem-detector --system-log-monitors=/config/kernel.monitor --apiserver-override="https://34.94.182.141:443?inClusterConfig=false&auth=/kubeconfig/npd.kubeconfig" --alsologtostderr 1>>/var/log/npd-$(NODE_NAME).log 2>&1
    State:          Running
      Started:      Thu, 03 Sep 2020 22:18:36 +0000
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:     20m
      memory:  20Mi
    Environment:
      NODE_NAME:  hollow-node-wht2t (v1:metadata.name)
    Mounts:
      /config from kernelmonitorconfig-volume (ro)
      /kubeconfig from kubeconfig-volume (ro)
      /var/log from logs-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from no-serviceaccount-access-to-real-master (ro)
Conditions:
  Type              Status
  Initialized       True
  ContainersReady   True
  Ready             True
  PodScheduled      True
Volumes:
  kubeconfig-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubeconfig
    Optional:    false
  kernelmonitorconfig-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      node-configmap
    Optional:  false
  logs-volume:
    Type:          HostPath (bare host directory volume)
    Path:          /var/log
    HostPathType:
  no-serviceaccount-access-to-real-master:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  default-token-8sfvh:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-8sfvh
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 900s
Events:          <none>
```
```
sonyali@sonya-uswest2:~/go/src/k8s.io/arktos$ kubectl describe pods hollow-node-h7cqt -n kubemark
Name:           hollow-node-h7cqt
Namespace:      kubemark
Tenant:         system
Priority:       0
Node:           etcd-3a1w1e-minion-group-zz2b/10.40.0.57
Start Time:     Thu, 03 Sep 2020 22:18:50 +0000
Labels:         name=hollow-node
Annotations:    <none>
Status:         Running
IP:             10.64.26.67
Controlled By:  ReplicationController/hollow-node
Init Containers:
  init-inotify-limit:
    Container ID:  unknown://0481a45b6bf614123e95df4f38f75c09f33c2e590840bc4d2789e688e698bfe8
    Image:         busybox
    Image ID:      docker-pullable://busybox@sha256:c2d41d2ba6d8b7b4a3ffec621578eb4d9a0909df29dfa2f6fd8a2e5fd0836aed
    Port:          <none>
    Host Port:     <none>
    Command:
      sysctl
      -w
      fs.inotify.max_user_instances=1000
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 03 Sep 2020 22:18:52 +0000
      Finished:     Thu, 03 Sep 2020 22:18:52 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-8sfvh (ro)
Containers:
  hollow-kubelet:
    Container ID:  unknown://35a5c88ec189b67e9db0c0eef9637a5d1890c0d465eb212b47cddee7dac5ec1b
    Image:         gcr.io/workload-controller-manager/kubemark:e4jpra
    Image ID:      docker-pullable://gcr.io/workload-controller-manager/kubemark@sha256:800505439f233a84d5dd54d3ed20f128c5363e4094839a34842a19218c43e3d1
    Ports:         4194/TCP, 10250/TCP, 10255/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP
    Command:
      /bin/sh
      -c
      /kubemark --morph=kubelet --name=$(NODE_NAME)  --v=4 --v=4 --kubeconfig=/kubeconfig/kubelet.kubeconfig $(CONTENT_TYPE) --alsologtostderr 1>>/var/log/kubelet-$(NODE_NAME).log 2>&1
    State:          Running
      Started:      Fri, 04 Sep 2020 15:20:35 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Fri, 04 Sep 2020 14:34:57 +0000
      Finished:     Fri, 04 Sep 2020 15:20:32 +0000
    Ready:          True
    Restart Count:  7
    Requests:
      cpu:     40m
      memory:  100M
    Environment:
      CONTENT_TYPE:  <set to the key 'content.type' of config map 'node-configmap'>  Optional: false
      NODE_NAME:     hollow-node-h7cqt (v1:metadata.name)
    Mounts:
      /kubeconfig from kubeconfig-volume (ro)
      /var/log from logs-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-8sfvh (ro)
  hollow-proxy:
    Container ID:  unknown://ef52bff4131b5f299347bbbf62839f09b89de942ee7bd334b17cf7d51a4419af
    Image:         gcr.io/workload-controller-manager/kubemark:e4jpra
    Image ID:      docker-pullable://gcr.io/workload-controller-manager/kubemark@sha256:800505439f233a84d5dd54d3ed20f128c5363e4094839a34842a19218c43e3d1
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      /kubemark --morph=proxy --name=$(NODE_NAME)  --v=4 --v=4 --kubeconfig=/kubeconfig/kubeproxy.kubeconfig $(CONTENT_TYPE) --alsologtostderr 1>>/var/log/kubeproxy-$(NODE_NAME).log 2>&1
    State:          Running
      Started:      Thu, 03 Sep 2020 22:18:53 +0000
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:     50m
      memory:  352400Ki
    Environment:
      CONTENT_TYPE:  <set to the key 'content.type' of config map 'node-configmap'>  Optional: false
      NODE_NAME:     hollow-node-h7cqt (v1:metadata.name)
    Mounts:
      /kubeconfig from kubeconfig-volume (ro)
      /var/log from logs-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-8sfvh (ro)
  hollow-node-problem-detector:
    Container ID:  unknown://dcc0f466838a91c38511423f23bd30009d136724ae22acc91704c5519bbbe6fa
    Image:         k8s.gcr.io/node-problem-detector:v0.4.1
    Image ID:      docker-pullable://k8s.gcr.io/node-problem-detector@sha256:f95cab985c26b2f46e9bd43283e0bfa88860c14e0fb0649266babe8b65e9eb2b
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      /node-problem-detector --system-log-monitors=/config/kernel.monitor --apiserver-override="https://34.94.182.141:443?inClusterConfig=false&auth=/kubeconfig/npd.kubeconfig" --alsologtostderr 1>>/var/log/npd-$(NODE_NAME).log 2>&1
    State:          Running
      Started:      Thu, 03 Sep 2020 22:18:53 +0000
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:     20m
      memory:  20Mi
    Environment:
      NODE_NAME:  hollow-node-h7cqt (v1:metadata.name)
    Mounts:
      /config from kernelmonitorconfig-volume (ro)
      /kubeconfig from kubeconfig-volume (ro)
      /var/log from logs-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from no-serviceaccount-access-to-real-master (ro)
Conditions:
  Type              Status
  Initialized       True
  ContainersReady   True
  Ready             True
  PodScheduled      True
Volumes:
  kubeconfig-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubeconfig
    Optional:    false
  kernelmonitorconfig-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      node-configmap
    Optional:  false
  logs-volume:
    Type:          HostPath (bare host directory volume)
    Path:          /var/log
    HostPathType:
  no-serviceaccount-access-to-real-master:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  default-token-8sfvh:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-8sfvh
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 900s
Events:          <none>
```

**Comment by pdgetrf** [comment]
the error is not just patch but with update 

![image](https://user-images.githubusercontent.com/252020/92290628-9e4e7300-eec9-11ea-89bf-2031cc24e1df.png)

**Comment by sonyafenge** [comment]
closing this issue because we are replacing multiapiserver with scale-out solution
