### ISSUE TITLE
kubelet stopped  per "panic: runtime error: index out of range" in sort.go

### ISSUE THREAD

**Issue by sonyafenge** [CentaurusInfra/arktos#687]
**What happened**:
Started a 10K nodes run with 3 apiserver, 3 workload, 1 etcd to verify this fix. Cluster crashed when create 100K -> 200K pods with this panic and kubelet stopped
```
Sep 04 22:04:45 node10k-3a2c1e-kubemark-master kubelet[2809]: panic: runtime error: index out of range
Sep 04 22:04:45 node10k-3a2c1e-kubemark-master kubelet[2809]: goroutine 126521 [running]:
Sep 04 22:04:45 node10k-3a2c1e-kubemark-master kubelet[2809]: internal/fmtsort.Sort(0x37a3e40, 0xc000a0c450, 0x15, 0x99)
Sep 04 22:04:45 node10k-3a2c1e-kubemark-master kubelet[2809]:         /usr/local/go/src/internal/fmtsort/sort.go:60 +0x34f
Sep 04 22:04:45 node10k-3a2c1e-kubemark-master kubelet[2809]: fmt.(*pp).printValue(0xc000702240, 0x37a3e40, 0xc000a0c450, 0x15, 0x76, 0x0)
Sep 04 22:04:45 node10k-3a2c1e-kubemark-master kubelet[2809]:         /usr/local/go/src/fmt/print.go:759 +0xd20
Sep 04 22:04:45 node10k-3a2c1e-kubemark-master kubelet[2809]: fmt.(*pp).printArg(0xc000702240, 0x37a3e40, 0xc000a0c450, 0x76)
Sep 04 22:04:45 node10k-3a2c1e-kubemark-master kubelet[2809]:         /usr/local/go/src/fmt/print.go:702 +0x2ba
Sep 04 22:04:45 node10k-3a2c1e-kubemark-master kubelet[2809]: fmt.(*pp).doPrintf(0xc000702240, 0x4102826, 0x2b, 0xc001cd7d88, 0x2, 0x2)
Sep 04 22:04:45 node10k-3a2c1e-kubemark-master kubelet[2809]:         /usr/local/go/src/fmt/print.go:1016 +0x158
Sep 04 22:04:45 node10k-3a2c1e-kubemark-master kubelet[2809]: fmt.Fprintf(0x47ce380, 0xc0006cb5e0, 0x4102826, 0x2b, 0xc0012d3d88, 0x2, 0x2, 0xc000c22510, 0x57e4ce, 0x3fbc240)
Sep 04 22:04:45 node10k-3a2c1e-kubemark-master kubelet[2809]:         /usr/local/go/src/fmt/print.go:199 +0x72
Sep 04 22:04:45 node10k-3a2c1e-kubemark-master kubelet[2809]: k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).printf(0x764a580, 0xc000000000, 0x4102826, 0x2b, 0xc0012d3d88, 0x2, 0x2)
Sep 04 22:04:45 node10k-3a2c1e-kubemark-master kubelet[2809]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:701 +0xc4
Sep 04 22:04:45 node10k-3a2c1e-kubemark-master kubelet[2809]: k8s.io/kubernetes/vendor/k8s.io/klog.Verbose.Infof(...)
Sep 04 22:04:45 node10k-3a2c1e-kubemark-master kubelet[2809]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:1156
Sep 04 22:04:45 node10k-3a2c1e-kubemark-master kubelet[2809]: k8s.io/kubernetes/vendor/k8s.io/client-go/apiserverupdate.SetAPIServerConfig(0xc000a0c450, 0xe880a4176)
Sep 04 22:04:45 node10k-3a2c1e-kubemark-master kubelet[2809]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/apiserverupdate/update.go:81 +0x51e
Sep 04 22:04:45 node10k-3a2c1e-kubemark-master kubelet[2809]: k8s.io/kubernetes/vendor/k8s.io/client-go/datapartition.setApiServerConfigMap.func2(0xc000b1c090)
Sep 04 22:04:45 node10k-3a2c1e-kubemark-master kubelet[2809]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/datapartition/apiserverconfigmanager.go:291 +0x9d
Sep 04 22:04:45 node10k-3a2c1e-kubemark-master kubelet[2809]: created by k8s.io/kubernetes/vendor/k8s.io/client-go/datapartition.setApiServerConfigMap
Sep 04 22:04:45 node10k-3a2c1e-kubemark-master kubelet[2809]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/datapartition/apiserverconfigmanager.go:285 +0x518
Sep 04 22:04:45 node10k-3a2c1e-kubemark-master systemd[1]: kubelet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 04 22:04:45 node10k-3a2c1e-kubemark-master systemd[1]: kubelet.service: Unit entered failed state.
Sep 04 22:04:45 node10k-3a2c1e-kubemark-master systemd[1]: kubelet.service: Failed with result 'exit-code'.
Sep 04 22:04:55 node10k-3a2c1e-kubemark-master systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Sep 04 22:04:55 node10k-3a2c1e-kubemark-master systemd[1]: Stopped Kubernetes kubelet.
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
logs can be found under GCP project: workload-controller-manager:
```
sonya-useast1:  /home/sonyali/logs/perf-test/gce-10000/arktos/0904-node10k-3a2c1e 
```
**Environment**:
- Arktos version (use `kubectl version`):
```
sonyali@sonya-useast1:~/go/src/k8s.io/arktos$ git log
commit 5e1cb3617a1131b0ebaf8c8b256134ba07c2758b
Author: Ying Huang <sindica2000@yahoo.com>
Date:   Fri Sep 4 18:37:28 2020 +0000

    Bug fix for API Server Config Update Notification (#678)

commit 0a6b63ed013c8f8438f55f3f2f3517bd4769ed67
Author: chenqianfzh <51831990+chenqianfzh@users.noreply.github.com>
Date:   Thu Sep 3 18:49:47 2020 -0700

    Multi tenancy/admission e2e tests (#673)

    * multi-tenancy admission e2e tests

    * address comments

commit 9fa1a561e4394d5b314a2ac32388848203d7ed4c
Author: Ying Huang <sindica2000@yahoo.com>
Date:   Thu Sep 3 21:09:51 2020 +0000

    Fix UT for unsorted enumeration. (#674)
```
and removed 
```
commit 7b181c4b246b0517b1230b9b4b2f5da255ca0cef
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by sonyafenge** [comment]
### 9/9/2020 [perf-tests][arktos][node5000][workloadDisabled] openfiles-3a0w1e
5k nodes run with 3 apiserver/0 workload/1 etcd(3.4.4) failed with this issue: https://github.com/futurewei-cloud/arktos/issues/701.
Further verifying is in progress

**Comment by sonyafenge** [comment]
### 9/10/2020 [perf-tests][arktos][node5000][workloadDisabled] openfiles-3a0w1e
5k nodes run with 3 apiserver/0 workload/1 etcd(3.4.4) and update master ulimit -n 200000, didn't get a repro for this isue.

```
commit 994de1da91763eeaec84a4cc0e979be7c9d16ffa
Author: sonyafenge <sonyafenge@gmail.com>
Date:   Wed Sep 9 02:51:40 2020 +0000

    ETCD3.4.4

commit 6028259e93e00e3b09906560d94e377efa5fd4f3
Author: sonyafenge <sonyafenge@gmail.com>
Date:   Fri Aug 28 21:32:26 2020 +0000

    disable workload-controller-manager

commit 4cee1c408be137d3d281ce8ed25eb80a2ef70775
Author: Ying Huang <sindica2000@yahoo.com>
Date:   Wed Sep 9 18:28:43 2020 +0000

    API server config read lock. (#692)
```
logs can be found under GCP project: workload-controller-manager:
```
sonya-uswest2:  /home/sonyali/logs/perf-test/gce-5000/arktos/0910-openfiles-3a0w1e 
```

**Comment by sonyafenge** [comment]
### 9/10/2020 [perf-tests][arktos][node5000][workloadDisabled] etcd344-3a0w1e
5k nodes run with 3 apiserver/0 workload/1 etcd(3.4.4) and use the default ulimit -n 1024 for master, didn't get a repro for this isue.
```
commit 994de1da91763eeaec84a4cc0e979be7c9d16ffa
Author: sonyafenge <sonyafenge@gmail.com>
Date:   Wed Sep 9 02:51:40 2020 +0000

    ETCD3.4.4

commit 6028259e93e00e3b09906560d94e377efa5fd4f3
Author: sonyafenge <sonyafenge@gmail.com>
Date:   Fri Aug 28 21:32:26 2020 +0000

    disable workload-controller-manager

commit 4cee1c408be137d3d281ce8ed25eb80a2ef70775
Author: Ying Huang <sindica2000@yahoo.com>
Date:   Wed Sep 9 18:28:43 2020 +0000

    API server config read lock. (#692)
```
logs can be found under GCP project: workload-controller-manager:
```
sonya-useast1:  /home/sonyali/logs/perf-test/gce-5000/arktos/0910-etcd344-3a0w1e 
```

**Comment by sonyafenge** [comment]
### 9/11/2020 [perf-tests][arktos]
Two runs on Friday, both disabled workload-controller-manager and has ETCD 3.4.4 with 3 apiserver, 0 workload, 1 wtcd:
1. 10K runs started from density testing,  density testing failed with 3 other issues, but no repro for this issue.
2. 5K runs started from load testing, load testing failed with 4 other issues, but no repro for this issue.

**Comment by sonyafenge** [comment]
close this issue because we are replacing multiapiserver with scale-out solution
